name = "Final_project"
uuid = "dde67b72-a4f2-4812-84c0-e08de78f3b84"
authors = ["Zijia-Liu"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
NaNStatistics = "b946abbf-3ea7-4610-9019-9858bfdeaf2d"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
